# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenizer < Formula
  desc "A fast CLI tool to count tokens for various Large Language Model (LLM) providers."
  homepage "https://github.com/zahidcakici/tokenizer-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zahidcakici/tokenizer-cli/releases/download/v0.1.4/tokenizer-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "17ce2667d9f3de550050659c0ebdebcf185416c47450d2923d341c18f29a8e44"

      def install
        bin.install "tokenizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zahidcakici/tokenizer-cli/releases/download/v0.1.4/tokenizer-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "8abfd8e5ea2a3ca6375f9a56a6b08bf77a27865020bccbc546ad367d0555e5ad"

      def install
        bin.install "tokenizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zahidcakici/tokenizer-cli/releases/download/v0.1.4/tokenizer-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "3c425e8c998cba12882482629b1df90ac3e3e9494b393fdaa49a6d613a8e84f0"
      def install
        bin.install "tokenizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zahidcakici/tokenizer-cli/releases/download/v0.1.4/tokenizer-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "15bb0fd6b7f62034d731faf3a39cc8bf1b402eb0c4e0d2fbc9f3a3221a1522b2"
      def install
        bin.install "tokenizer"
      end
    end
  end

  test do
    system "#{bin}/tokenizer", "--help"
  end
end
